# Generated by Django 5.2.3 on 2025-06-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_address_order_city_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
